image: node:latest

build:
  stage: build
  script:
    - yarn
    - npm run generate
  artifacts:
    paths:
    - dist/

deploy_production:
  stage: deploy
  environment:
    name: production
  only:
    - master
  dependencies:
    - build
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY santihans-5a517
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
